[package]
name = "lifering"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A Hash wrapper around floats."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
